name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the main branch
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH client
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa 35.170.185.200 >> ~/.ssh/known_hosts

      # Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@35.170.185.200 << 'EOF'
            # Navigate to your project directory
            cd /path/to/your/project/directory

            # Pull the latest changes from the GitHub repository
            git pull origin main
          EOF
